deepseek-ai/deepseek-moe-16b-base
phi_3_mini|microsoft/phi-3-mini-4k-instruct
gemma_7b|google/gemma-7b-it
llama3_1_8b|meta-llama/Llama-3.1-8B-Instruct
qwen2_5_7b|Qwen/Qwen2.5-7B-Instruct
mistral_7b|mistralai/Mistral-7B-Instruct-v0.3
#nemotron_nano_9b|nvidia/NVIDIA-Nemotron-Nano-9B-v2
#mixtral_8x7b|mistralai/Mixtral-8x7B-Instruct-v0.1