#mixtral_8x7b|mistralai/Mixtral-8x7B-Instruct-v0.1
#phi_3_mini|microsoft/phi-3-mini-4k-instruct
gemma_7b|google/gemma-7b-it
nemotron_4_8b|nvidia/Nemotron-4-8B-Instruct
llama3_1_8b|meta-llama/Llama-3.1-8B-Instruct
qwen2_5_7b|Qwen/Qwen2.5-7B-Instruct
mistral_7b|mistralai/Mistral-7B-Instruct-v0.3